<a href="https://colab.research.google.com/github/M-TALH007/insurance/blob/main/insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=3000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 11ms/step - loss: 0.6253 - accuracy: 0.6364
Epoch 502/3000
1/1 [==============================] - 0s 12ms/step - loss: 0.6252 - accuracy: 0.6364
Epoch 503/3000
1/1 [==============================] - 0s 11ms/step - loss: 0.6252 - accuracy: 0.6364
Epoch 504/3000
1/1 [==============================] - 0s 10ms/step - loss: 0.6251 - accuracy: 0.6364
Epoch 505/3000
1/1 [==============================] - 0s 10ms/step - loss: 0.6251 - accuracy: 0.6364
Epoch 506/3000
1/1 [==============================] - 0s 10ms/step - loss: 0.6250 - accuracy: 0.6364
Epoch 507/3000
1/1 [==============================] - 0s 11ms/step - loss: 0.6250 - accuracy: 0.6364
Epoch 508/3000
1/1 [==============================] - 0s 9ms/step - loss: 0.6249 - accuracy: 0.6364
Epoch 509/3000
1/1 [==============================] - 0s 10ms/step - loss: 0.6249 - accuracy: 0.6364
Epoch 510/3000
1/1 [==============================] - 0s

In [ ]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 168ms/step - loss: 0.4515 - accuracy: 0.8333


[0.4515165090560913, 0.8333333134651184]

In [ ]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 76ms/step


array([[0.67709565],
       [0.45932952],
       [0.25552067],
       [0.53705925],
       [0.690566  ],
       [0.7643411 ]], dtype=float32)

In [ ]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [ ]:
coef, intercept = model.get_weights()

In [ ]:
coef, intercept

(array([[3.1155128],
        [1.1555806]], dtype=float32),
 array([-1.879415], dtype=float32))

In [ ]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [ ]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

0.6770956898878387